services: 
  app:
    image: facundo1cabrera/openjiraclon:1.0.0
    container_name: next-app
    ports:
      - ${PORT}:${PORT}
    environment:
      MONGO_URL: ${MONGO_URL}
      NODE_ENV: ${NODE_ENV}

  entriesdb: 
    image: mongo:5.0.0
    container_name: entries_database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db